name: mobile_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  responsive_sizer: ^3.3.1
  intl: ^0.19.0
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.4.3
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  email_validator: ^3.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
