// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClzuHppegvZogwPJK23zdRsmmDQxEHZec',
    appId: '1:19841551899:web:75f971d4343fa09f8e72be',
    messagingSenderId: '19841551899',
    projectId: 'clotheslinemobile',
    authDomain: 'clotheslinemobile.firebaseapp.com',
    databaseURL: 'https://clotheslinemobile-default-rtdb.firebaseio.com',
    storageBucket: 'clotheslinemobile.firebasestorage.app',
    measurementId: 'G-8NS2M8KXDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrClIl4zLg-Kc91wDf5l_Whdbv5XEUmNs',
    appId: '1:19841551899:android:18d2224837bef05d8e72be',
    messagingSenderId: '19841551899',
    projectId: 'clotheslinemobile',
    databaseURL: 'https://clotheslinemobile-default-rtdb.firebaseio.com',
    storageBucket: 'clotheslinemobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqfDRl23RZkMb-RPZNfOTLAV0-OXgOUuw',
    appId: '1:19841551899:ios:456b806b47fa057c8e72be',
    messagingSenderId: '19841551899',
    projectId: 'clotheslinemobile',
    databaseURL: 'https://clotheslinemobile-default-rtdb.firebaseio.com',
    storageBucket: 'clotheslinemobile.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqfDRl23RZkMb-RPZNfOTLAV0-OXgOUuw',
    appId: '1:19841551899:ios:456b806b47fa057c8e72be',
    messagingSenderId: '19841551899',
    projectId: 'clotheslinemobile',
    databaseURL: 'https://clotheslinemobile-default-rtdb.firebaseio.com',
    storageBucket: 'clotheslinemobile.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClzuHppegvZogwPJK23zdRsmmDQxEHZec',
    appId: '1:19841551899:web:d0597c1bc3544cd88e72be',
    messagingSenderId: '19841551899',
    projectId: 'clotheslinemobile',
    authDomain: 'clotheslinemobile.firebaseapp.com',
    databaseURL: 'https://clotheslinemobile-default-rtdb.firebaseio.com',
    storageBucket: 'clotheslinemobile.firebasestorage.app',
    measurementId: 'G-4BVXG7HQR6',
  );
}
